model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 128

exp_params:
  dataset: xray
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  val_split: 0.25
  patch_size: 128
  overlap: 0.25
  manual_seed: 1265

trainer_params:
  max_epochs: 80

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265